Repository dogaegirl6mo/Dokgi, pull requests merged in 2024-07, with the labels that each got.

#186 [Fix] 오류수정 4차
  Dokgi.xcodeproj/project.pbxproj
  Dokgi/Extension/TextFieldExtension.swift
  Dokgi/Resource/Assets.xcassets/icons/backicon.imageset/Contents.json
  Dokgi/Resource/Assets.xcassets/icons/backicon.imageset/ion_caret-back.svg
  Dokgi/View/AddPassageView/View/AddPassageContainerView.swift
  Dokgi/View/AddPassageView/ViewController/AddPassageViewController.swift
  Dokgi/View/AddPassageView/ViewController/BookSearchViewController.swift
  Dokgi/View/BookDetailView/ViewController/BookDetailViewController.swift
  Dokgi/View/Components/CustomNavigationController.swift
  Dokgi/View/PassageDetailView/View/PassageDetailContainerView.swift
  Dokgi/View/PassageDetailView/ViewController/PassageDetailViewController.swift
  Dokgi/View/PassageView/Cell/PassageCollectionViewCell.swift
  Dokgi/View/PassageView/ViewController/PassageViewController.swift
  Dokgi/View/SettingView/ViewController/SettingViewController.swift
  Dokgi/View/TabBarView/TabBarViewController.swift
  Dokgi/ViewModel/SettingViewModel/DayTimeViewModel.swift
Labels: 🐞 BugFix

#187 OCR 기능 개선
  Dokgi/Resource/Assets.xcassets/Color/allClearGrey.colorset/Contents.json
  Dokgi/View/AddPassageView/View/AddPassageContainerView.swift
  Dokgi/View/AddPassageView/View/BookSearchContainerView.swift
  Dokgi/View/AddPassageView/ViewController/AddPassageViewController.swift
  Dokgi/ViewModel/AddPassageViewModel/AddPassageViewModel.swift
Labels: ✨ Feature

#188 Feat/#175 CloudKit
  Dokgi.xcodeproj/project.pbxproj
  Dokgi/Application/AppDelegate.swift
  Dokgi/Application/SceneDelegate.swift
  Dokgi/Dokgi.entitlements
  Dokgi/Dokgi.xcdatamodeld/Dokgi 2.xcdatamodel/contents
  Dokgi/DokgiV1ToV2MigrationPolicy.swift
  Dokgi/Extension/UICollectionViewCellExtension.swift
  Dokgi/Info.plist
  Dokgi/Model/CoreData/CoreDataManager.swift
  Dokgi/View/BookDetailView/ViewController/BookDetailViewController.swift
  Dokgi/View/Components/BaseLibraryAndPassageViewController.swift
  Dokgi/View/HomeView/Cell/CurrentLevelCell.swift
  Dokgi/View/HomeView/Cell/TodayPassageCell.swift
  Dokgi/View/HomeView/View/HomeView.swift
  Dokgi/View/HomeView/ViewController/HomeViewController.swift
  Dokgi/View/LibraryView/ViewController/LibraryViewController.swift
  Dokgi/View/PassageView/ViewController/PassageViewController.swift
  Dokgi/ViewModel/BookDetailViewModel/BookDetailViewModel.swift
  Dokgi/ViewModel/HomeViewModel/HomeViewModel.swift
  Dokgi/ViewModel/PassageViewModel/PassageViewModel.swift
  DokgiWidget/DokgiWidget.swift
  DokgiWidgetExtension.entitlements
Labels: ✨ Feature

#193 [Fix] 네비게이션 및 구절상세 키워드 수정
  Dokgi/View/Components/CustomNavigationController.swift
  Dokgi/View/PassageDetailView/View/PassageDetailContainerView.swift
  Dokgi/View/SettingView/ViewController/SettingViewController.swift
Labels: 🐞 BugFix

#196 Fix/#191 오류 수정 5차 구절 추가
  Dokgi/View/AddPassageView/ViewController/BookSearchViewController.swift
  Dokgi/ViewModel/HomeViewModel/HomeViewModel.swift
Labels: 🐞 BugFix

#195 [Fix]#194-서재오류 해결
  Dokgi/View/AddPassageView/ViewController/AddPassageViewController.swift
  Dokgi/View/BookDetailView/ViewController/BookDetailViewController.swift
Labels: 🐞 BugFix

#198 [Fix] 오류 5차 수정 구절 화면
  Dokgi/View/PassageView/ViewController/PassageViewController.swift
Labels: 🐞 BugFix

#200 [Fix]#199-홈화면오류수정
  Dokgi.xcodeproj/project.pbxproj
  Dokgi/View/HomeView/Cell/CurrentLevelCell.swift
  Dokgi/View/HomeView/ViewController/HomeViewController.swift
  Dokgi/View/PassageView/ViewController/PassageViewController.swift
  Dokgi/ViewModel/HomeViewModel/HomeViewModel.swift
  Dokgi/ViewModel/PassageDetailViewModel/PassageDetailViewModel.swift
Labels: 🐞 BugFix

#202 [Fix]#201-오류 7차
  Dokgi.xcodeproj/project.pbxproj
  Dokgi/View/Components/BaseLibraryAndPassageViewController.swift
  Dokgi/View/PassageView/ViewController/PassageViewController.swift
Labels: 🐞 BugFix

#203 Ver 1.1
  Dokgi.xcodeproj/project.pbxproj
  Dokgi/Application/AppDelegate.swift
  Dokgi/Application/SceneDelegate.swift
  Dokgi/Dokgi.entitlements
  Dokgi/Dokgi.xcdatamodeld/Dokgi 2.xcdatamodel/contents
  Dokgi/DokgiV1ToV2MigrationPolicy.swift
  Dokgi/Extension/TextFieldExtension.swift
  Dokgi/Extension/UICollectionViewCellExtension.swift
  Dokgi/Info.plist
  Dokgi/Model/CoreData/CoreDataManager.swift
  Dokgi/Resource/Assets.xcassets/Color/allClearGrey.colorset/Contents.json
  Dokgi/Resource/Assets.xcassets/icons/backicon.imageset/Contents.json
  Dokgi/Resource/Assets.xcassets/icons/backicon.imageset/ion_caret-back.svg
  Dokgi/View/AddPassageView/View/AddPassageContainerView.swift
  Dokgi/View/AddPassageView/View/BookSearchContainerView.swift
  Dokgi/View/AddPassageView/ViewController/AddPassageViewController.swift
  Dokgi/View/AddPassageView/ViewController/BookSearchViewController.swift
  Dokgi/View/BookDetailView/ViewController/BookDetailViewController.swift
  Dokgi/View/Components/BaseLibraryAndPassageViewController.swift
  Dokgi/View/Components/CustomNavigationController.swift
  Dokgi/View/HomeView/Cell/CurrentLevelCell.swift
  Dokgi/View/HomeView/Cell/TodayPassageCell.swift
  Dokgi/View/HomeView/View/HomeView.swift
  Dokgi/View/HomeView/ViewController/HomeViewController.swift
  Dokgi/View/LibraryView/ViewController/LibraryViewController.swift
  Dokgi/View/PassageDetailView/View/PassageDetailContainerView.swift
  Dokgi/View/PassageDetailView/ViewController/PassageDetailViewController.swift
  Dokgi/View/PassageView/Cell/PassageCollectionViewCell.swift
  Dokgi/View/PassageView/ViewController/PassageViewController.swift
  Dokgi/View/SettingView/ViewController/SettingViewController.swift
  Dokgi/View/TabBarView/TabBarViewController.swift
  Dokgi/ViewModel/AddPassageViewModel/AddPassageViewModel.swift
  Dokgi/ViewModel/BookDetailViewModel/BookDetailViewModel.swift
  Dokgi/ViewModel/HomeViewModel/HomeViewModel.swift
  Dokgi/ViewModel/PassageDetailViewModel/PassageDetailViewModel.swift
  Dokgi/ViewModel/PassageViewModel/PassageViewModel.swift
  Dokgi/ViewModel/SettingViewModel/DayTimeViewModel.swift
  DokgiWidget/DokgiWidget.swift
  DokgiWidgetExtension.entitlements
  README.md
Labels: 🌏 Deploy
