Repository dogaegirl6mo/Dokgi, pull requests merged in 2024-06, with the labels that each got.

#2 [Feat] API 연결
  Dokgi.xcodeproj/project.pbxproj
  Dokgi/Info.plist
  Dokgi/Model/BookModel.swift
  Dokgi/Network/BookManager.swift
  Dokgi/Network/Network.swift
Labels: 📬 API

#14 Feat/#11
  Dokgi.xcodeproj/project.pbxproj
  Dokgi.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Dokgi/Application/SceneDelegate.swift
  Dokgi/View/AddVerseVC.swift
  Dokgi/View/TabBarVC.swift
Labels: ✨ Feature

#17 Feat/#6 설정화면구현 및 폰트추가
  Dokgi.xcodeproj/project.pbxproj
  Dokgi/Application/AppDelegate.swift
  Dokgi/Application/SceneDelegate.swift
  Dokgi/Extension/IntArrayExtension.swift
  Dokgi/Font.swift
  Dokgi/Info.plist
  Dokgi/Model/UserDefaultsKey.swift
  Dokgi/Resource/Assets.xcassets/icons/check2.imageset/Contents.json
  Dokgi/Resource/Assets.xcassets/icons/check2.imageset/check2.svg
  Dokgi/Resource/Font/Pretendard-Bold.otf
  Dokgi/Resource/Font/Pretendard-Medium.otf
  Dokgi/Resource/Font/Pretendard-Regular.otf
  Dokgi/Resource/Font/Pretendard-SemiBold.otf
  Dokgi/View/SettingView/AlarmView.swift
  Dokgi/View/SettingView/DaySelectViewController.swift
  Dokgi/View/SettingView/DayTableViewCell.swift
  Dokgi/View/SettingView/SettingViewController.swift
  Dokgi/View/SettingView/TimePickerViewController.swift
  Dokgi/View/ViewController.swift
  Dokgi/ViewModel/DayTimeViewModel.swift
Labels: ✨ Feature

#21 위젯 만들기
  Dokgi.xcodeproj/project.pbxproj
  DokgiWidget/Assets.xcassets/AccentColor.colorset/Contents.json
  DokgiWidget/Assets.xcassets/AppIcon.appiconset/Contents.json
  DokgiWidget/Assets.xcassets/Contents.json
  DokgiWidget/Assets.xcassets/WidgetBackground.colorset/Contents.json
  DokgiWidget/Assets.xcassets/doubleQuotationMarks.imageset/Contents.json
  DokgiWidget/Assets.xcassets/doubleQuotationMarks.imageset/doubleQuotationMarks1.svg
  DokgiWidget/DokgiWidget.swift
  DokgiWidget/DokgiWidgetBundle.swift
  DokgiWidget/Info.plist
Labels: ✨ Feature

#18 Feat/#16 스캔화면
  Dokgi.xcodeproj/project.pbxproj
  Dokgi/Info.plist
  Dokgi/View/AddVerseVC.swift
  Dokgi/View/TabBarVC.swift
Labels: ✨ Feature

#32 Feat/#26 구절작성화면 UI수정 & 책 검색 기능
  Dokgi.xcodeproj/project.pbxproj
  Dokgi.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Dokgi/Network/BookManager.swift
  Dokgi/View/AddVerse/AddVerseVC.swift
  Dokgi/View/AddVerse/BookCell.swift
  Dokgi/View/AddVerse/BookSearchVC.swift
  Dokgi/View/AddVerse/KeywordCell.swift
  Dokgi/View/AddVerseVC.swift
Labels: 🔧 Chore, ✨ Feature

#35 Feat/#28 플로팅 버튼 구현
  Dokgi.xcodeproj/project.pbxproj
  Dokgi/View/HomeView/CurrentLevelCell.swift
  Dokgi/View/HomeView/CurrentLevelCollectionFlowLayout.swift
  Dokgi/View/HomeView/HomeViewController.swift
  Dokgi/View/TabBarVC.swift
Labels: ✨ Feature

#40 [Feat] 구절 추가 화면 기능 구현
  Dokgi.xcodeproj/project.pbxproj
  Dokgi/Model/BookModel.swift
  Dokgi/Model/VerseModel.swift
  Dokgi/Network/BookManager.swift
  Dokgi/View/AddVerse/AddVerseVC.swift
  Dokgi/View/AddVerse/BookSearchVC.swift
  Dokgi/View/AddVerse/KeywordCell.swift
Labels: ✨ Feature

#38 [Feat] detailview 기능구현 및 코어데이터 수정
  Dokgi.xcodeproj/project.pbxproj
  Dokgi/Dokgi.xcdatamodeld/Dokgi.xcdatamodel/contents
  Dokgi/Model/CoreDataModel.swift
  Dokgi/Model/VerseModel.swift
  Dokgi/View/ ParagraphDetailView/KeywordCollectionViewCell.swift
  Dokgi/View/ ParagraphDetailView/ParagraphDetailContainerView.swift
  Dokgi/View/ ParagraphDetailView/ParagraphDetailViewController.swift
  Dokgi/View/AddVerse/AddVerseVC.swift
  Dokgi/View/LibraryView/LibrarySearchViewController.swift
  Dokgi/ViewModel/CoreDataManager.swift
  Dokgi/ViewModel/ParagraphDetailViewModel.swift
Labels: ✨ Feature

#43 Feat/#36 오늘의 구절 구현
  Dokgi.xcodeproj/project.pbxproj
  Dokgi/Font.swift
  Dokgi/Info.plist
  Dokgi/Resource/Assets.xcassets/Color/DotBlue.colorset/Contents.json
  Dokgi/Resource/Assets.xcassets/Color/DotGray.colorset/Contents.json
  Dokgi/Resource/Font/Pretendard-ExtraBold.otf
  Dokgi/View/HomeView/CurrentLevelCell.swift
  Dokgi/View/HomeView/HomeViewController.swift
  Dokgi/View/HomeView/TodayVersesCell.swift
  Dokgi/View/TabBarVC.swift
  Dokgi/ViewModel/HomeViewModel.swift
Labels: ✨ Feature

#45 [Feat]#39-DetailViewModel수정
  Dokgi/View/ ParagraphDetailView/ParagraphDetailViewController.swift
  Dokgi/ViewModel/ParagraphDetailViewModel.swift
Labels: ✨ Feature

#49 Feat/#47 플로팅 버튼
  Dokgi.xcodeproj/project.pbxproj
  Dokgi/View/AddVerse/AddVerseVC.swift
  Dokgi/View/FloatButton.swift
  Dokgi/View/HomeView/HomeViewController.swift
  Dokgi/View/LibraryView/LibrarySearchViewController.swift
  Dokgi/View/ParagraphView/ParagraphViewController.swift
  Dokgi/View/TabBarVC.swift
Labels: ✨ Feature

#54 Feat/#42 작성화면 UI 디테일
  Dokgi.xcodeproj/project.pbxproj
  Dokgi.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Dokgi/Application/AppDelegate.swift
  Dokgi/Network/BookManager.swift
  Dokgi/View/AddVerseView/AddVerseVC.swift
  Dokgi/View/AddVerseView/BookCell.swift
  Dokgi/View/AddVerseView/BookSearchVC.swift
  Dokgi/View/AddVerseView/KeywordCell.swift
Labels: 🎨 UIDesign

#53 [Design]UI디테일 수정
  Dokgi.xcodeproj/project.pbxproj
  Dokgi/Extension/DateExtension.swift
  Dokgi/Extension/StringExtension.swift
  Dokgi/Resource/Assets.xcassets/Color/ButtonLightGray.colorset/Contents.json
  Dokgi/View/ ParagraphDetailView/ParagraphDetailContainerView.swift
  Dokgi/View/ ParagraphDetailView/ParagraphDetailViewController.swift
  Dokgi/View/AddVerseView/AddVerseVC.swift
  Dokgi/View/AddVerseView/BookCell.swift
  Dokgi/View/AddVerseView/BookSearchVC.swift
  Dokgi/View/AddVerseView/KeywordCell.swift
  Dokgi/View/BookDetailView/BookDetailViewController.swift
  Dokgi/View/BookDetailView/PassageTableViewCell.swift
  Dokgi/View/HomeView/HomeViewController.swift
  Dokgi/View/HomeView/TodayVersesCell.swift
  Dokgi/View/LibraryView/LibrarySearchViewController.swift
  Dokgi/View/ParagraphView/ParagraphCollectionViewCell.swift
  Dokgi/View/ParagraphView/ParagraphViewController.swift
  Dokgi/View/SettingView/AlarmView.swift
  Dokgi/View/SettingView/DaySelectViewController.swift
  Dokgi/View/SettingView/DayTableViewCell.swift
  Dokgi/View/SettingView/SettingViewController.swift
  Dokgi/View/SettingView/TimePickerViewController.swift
  Dokgi/View/TabBarVC.swift
  Dokgi/View/ViewController.swift
Labels: 🎨 UIDesign

#51 Feat/#50 오늘의 구절 예외처리
  Dokgi/View/HomeView/HomeViewController.swift
  Dokgi/ViewModel/HomeViewModel.swift
Labels: ✨ Feature

#56 책 상세화면 데이터 넘겨주기
  Dokgi.xcodeproj/project.pbxproj
  Dokgi/Resource/Assets.xcassets/Color/BorderGray.colorset/Contents.json
  Dokgi/View/AddVerseView/AddVerseVC.swift
  Dokgi/View/AddVerseView/KeywordCell.swift
  Dokgi/View/BookDetailView/BookDetailViewController.swift
  Dokgi/View/BookDetailView/PassageTableViewCell.swift
  Dokgi/View/FloatButton.swift
  Dokgi/View/LibraryView/LibraryCollectionViewCell.swift
  Dokgi/View/LibraryView/LibrarySearchViewController.swift
  Dokgi/View/TabBarVC.swift
  Dokgi/ViewModel/BookDetailViewModel.swift
  Dokgi/ViewModel/CoreDataManager.swift
Labels: ✨ Feature

#57 Feat/#52 메인화면 CoreData 연결
  Dokgi/View/HomeView/HomeViewController.swift
  Dokgi/ViewModel/HomeViewModel.swift
Labels: ✨ Feature

#61 [Feat]#58-page segment구현
  Dokgi.xcodeproj/project.pbxproj
  Dokgi/Model/VerseModel.swift
  Dokgi/View/ ParagraphDetailView/ParagraphDetailContainerView.swift
  Dokgi/View/ ParagraphDetailView/ParagraphDetailViewController.swift
  Dokgi/View/SegmentControlView.swift
  Dokgi/ViewModel/ParagraphDetailViewModel.swift
Labels: ✨ Feature

#62 책 상세화면 데이터 반영, 탭바 블러
  Dokgi.xcodeproj/project.pbxproj
  Dokgi/View/BookDetailView/BookDetailViewController.swift
  Dokgi/View/HomeView/HomeViewController.swift
  Dokgi/View/LibraryView/LibrarySearchViewController.swift
  Dokgi/View/TabBarVC.swift
  Dokgi/ViewModel/BookDetailViewModel.swift
  Dokgi/ViewModel/CoreDataManager.swift
Labels: ✨ Feature

#63 Feat/#55 구절 추가 화면 기능 수정
  Dokgi/Network/BookManager.swift
  Dokgi/View/AddVerseView/AddVerseVC.swift
  Dokgi/View/AddVerseView/BookSearchVC.swift
Labels: ✨ Feature

#64 Feat/#60 오늘의 구절 인디케이터 및 구절추가시 홈에 반영
  Dokgi/View/HomeView/CurrentLevelCell.swift
  Dokgi/View/HomeView/HomeViewController.swift
  Dokgi/ViewModel/HomeViewModel.swift
Labels: 🐞 BugFix

#71 Feat/#66 AddVerseVC 파일 분리
  Dokgi.xcodeproj/project.pbxproj
  Dokgi/View/AddVerseView/AddVerseContainerView.swift
  Dokgi/View/AddVerseView/AddVerseVC.swift
  Dokgi/View/AddVerseView/KeywordCell.swift
  Dokgi/View/BookDetailView/BookDetailViewController.swift
  Dokgi/ViewModel/AddVerseViewModel.swift
Labels: ✨ Feature

#73 구절, 구절상세 데이터 연결
  Dokgi.xcodeproj/project.pbxproj
  Dokgi/View/BookDetailView/BookDetailViewController.swift
  Dokgi/View/ParagraphDetailView/KeywordCollectionViewCell.swift
  Dokgi/View/ParagraphDetailView/ParagraphDetailContainerView.swift
  Dokgi/View/ParagraphDetailView/ParagraphDetailViewController.swift
  Dokgi/View/ParagraphView/ParagraphViewController.swift
  Dokgi/ViewModel/BookDetailViewModel.swift
  Dokgi/ViewModel/ParagraphDetailViewModel.swift
  Dokgi/ViewModel/ParagraphViewModel.swift
Labels: ✨ Feature

#74 Design/#72 구절 작성화면 디테일
  Dokgi/View/AddVerseView/AddVerseContainerView.swift
  Dokgi/View/AddVerseView/AddVerseVC.swift
  Dokgi/View/AddVerseView/BookCell.swift
  Dokgi/View/AddVerseView/BookSearchVC.swift
Labels: 🎨 UIDesign

#76 [Feat] 알림설정 화면 오류 수정 및 alert 구현
  Dokgi/Application/AppDelegate.swift
  Dokgi/Model/UserDefaultsKey.swift
  Dokgi/Resource/Assets.xcassets/Color/BrightBlue.colorset/Contents.json
  Dokgi/Resource/Assets.xcassets/Color/LavenderBlue.colorset/Contents.json
  Dokgi/Resource/Assets.xcassets/Color/LavenderDarkBlue.colorset/Contents.json
  Dokgi/View/SettingView/AlarmView.swift
  Dokgi/View/SettingView/SettingViewController.swift
  Dokgi/View/SettingView/TimePickerViewController.swift
  Dokgi/ViewModel/DayTimeViewModel.swift
Labels: ✨ Feature

#77 [Design]#67-다음레벨셀 디자인 변경
  Dokgi/View/HomeView/CurrentLevelCell.swift
  Dokgi/View/HomeView/HomeViewController.swift
  Dokgi/ViewModel/HomeViewModel.swift
Labels: 🎨 UIDesign

#80 Feat/#69 앱 아이콘 및 런치스크린
  Dokgi/Application/AppDelegate.swift
  Dokgi/Base.lproj/LaunchScreen.storyboard
  Dokgi/Resource/Assets.xcassets/AppIcon.appiconset/100.png
  Dokgi/Resource/Assets.xcassets/AppIcon.appiconset/1024.png
  Dokgi/Resource/Assets.xcassets/AppIcon.appiconset/114.png
  Dokgi/Resource/Assets.xcassets/AppIcon.appiconset/120.png
  Dokgi/Resource/Assets.xcassets/AppIcon.appiconset/144.png
  Dokgi/Resource/Assets.xcassets/AppIcon.appiconset/152.png
  Dokgi/Resource/Assets.xcassets/AppIcon.appiconset/167.png
  Dokgi/Resource/Assets.xcassets/AppIcon.appiconset/180.png
  Dokgi/Resource/Assets.xcassets/AppIcon.appiconset/20.png
  Dokgi/Resource/Assets.xcassets/AppIcon.appiconset/29.png
  Dokgi/Resource/Assets.xcassets/AppIcon.appiconset/40.png
  Dokgi/Resource/Assets.xcassets/AppIcon.appiconset/50.png
  Dokgi/Resource/Assets.xcassets/AppIcon.appiconset/57.png
  Dokgi/Resource/Assets.xcassets/AppIcon.appiconset/58.png
  Dokgi/Resource/Assets.xcassets/AppIcon.appiconset/60.png
  Dokgi/Resource/Assets.xcassets/AppIcon.appiconset/72.png
  Dokgi/Resource/Assets.xcassets/AppIcon.appiconset/76.png
  Dokgi/Resource/Assets.xcassets/AppIcon.appiconset/80.png
  Dokgi/Resource/Assets.xcassets/AppIcon.appiconset/87.png
  Dokgi/Resource/Assets.xcassets/AppIcon.appiconset/Contents.json
  Dokgi/Resource/Assets.xcassets/images/dogki LaunchScreen.imageset/Contents.json
  Dokgi/Resource/Assets.xcassets/images/dogki LaunchScreen.imageset/dogki LaunchScreen 1x.png
  Dokgi/Resource/Assets.xcassets/images/dogki LaunchScreen.imageset/dogki LaunchScreen 2x.png
  Dokgi/Resource/Assets.xcassets/images/dogki LaunchScreen.imageset/dogki LaunchScreen.png
Labels: ✨ Feature

#81 [Feat]#78-내서재 기능수정
  Dokgi.xcodeproj/project.pbxproj
  Dokgi/View/LibraryView/LibraryCollectionViewCell.swift
  Dokgi/View/LibraryView/LibrarySearchViewController.swift
  Dokgi/ViewModel/LibrarySearchViewModel.swift
Labels: ✨ Feature

#82 Feat/#75 구절 추가 책 검색화면 최근검색어
  Dokgi.xcodeproj/project.pbxproj
  Dokgi/Info.plist
  Dokgi/Model/UserDefaultsKey.swift
  Dokgi/Resource/Assets.xcassets/icons/deleteRecentSearch.imageset/Contents.json
  Dokgi/Resource/Assets.xcassets/icons/deleteRecentSearch.imageset/deleteRecentSearche.svg
  Dokgi/Resource/Assets.xcassets/icons/poundKey.imageset/Contents.json
  Dokgi/Resource/Assets.xcassets/icons/poundKey.imageset/_poundKey.svg
  Dokgi/View/AddVerseView/AddVerseContainerView.swift
  Dokgi/View/AddVerseView/AddVerseVC.swift
  Dokgi/View/AddVerseView/BookCell.swift
  Dokgi/View/AddVerseView/BookSearchVC.swift
  Dokgi/View/AddVerseView/RecentSearchCell.swift
  Dokgi/View/BookDetailView/BookDetailViewController.swift
  Dokgi/View/ParagraphDetailView/ParagraphDetailViewController.swift
  Dokgi/View/SegmentControlView.swift
  Dokgi/ViewModel/AddVerseViewModel.swift
  Dokgi/ViewModel/BookSearchViewModel.swift
  Dokgi/ViewModel/ParagraphDetailViewModel.swift
Labels: ✨ Feature

#84 위젯 데이터 연결
  Dokgi.xcodeproj/project.pbxproj
  Dokgi.xcodeproj/project.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings
  Dokgi/Dokgi.entitlements
  Dokgi/Model/Model.swift
  Dokgi/Network/Network.swift
  Dokgi/ViewModel/CoreDataManager.swift
  Dokgi/ViewModel/ViewModel.swift
  DokgiWidget/DokgiWidget.swift
  DokgiWidgetExtension.entitlements
Labels: ✨ Feature

#85 Fix/#83 오류수정
  Dokgi/Extension/StringExtension.swift
  Dokgi/View/BookDetailView/BookDetailViewController.swift
  Dokgi/View/HomeView/HomeViewController.swift
  Dokgi/View/LibraryView/LibrarySearchViewController.swift
  Dokgi/View/ParagraphDetailView/ParagraphDetailViewController.swift
  Dokgi/View/ParagraphView/ParagraphViewController.swift
  Dokgi/ViewModel/CoreDataManager.swift
  Dokgi/ViewModel/ParagraphDetailViewModel.swift
  Dokgi/ViewModel/ParagraphViewModel.swift
Labels: 🐞 BugFix

#89 [Fix]#87-메인화면 버그 수정
  Dokgi/View/HomeView/CurrentLevelCell.swift
  Dokgi/View/HomeView/HomeViewController.swift
  Dokgi/ViewModel/HomeViewModel.swift
Labels: 🐞 BugFix

#90 [Feat] 구절상세화면 버그 수정
  Dokgi/View/ParagraphDetailView/KeywordCollectionViewCell.swift
  Dokgi/View/ParagraphDetailView/ParagraphDetailContainerView.swift
  Dokgi/View/ParagraphDetailView/ParagraphDetailViewController.swift
  Dokgi/ViewModel/ParagraphDetailViewModel.swift
Labels: 🐞 BugFix

#99 [Fix]#95-내 구절 정렬 오류 수정
  Dokgi/View/ParagraphView/ParagraphViewController.swift
Labels: 🐞 BugFix

#98 [Fix]#93-책상세 구절 잘리는 오류 수정
  Dokgi/View/BookDetailView/BookDetailViewController.swift
Labels: 🐞 BugFix

#92 [Fix]#91-내서재 정렬수정
  Dokgi/View/LibraryView/LibraryCollectionViewCell.swift
  Dokgi/View/LibraryView/LibrarySearchViewController.swift
Labels: 🐞 BugFix

#101 [Fix]#100-구절 상세 페이지 alert구현
  Dokgi/View/LibraryView/LibrarySearchViewController.swift
  Dokgi/View/ParagraphDetailView/ParagraphDetailViewController.swift
Labels: 🐞 BugFix

#103 [Setting]#102-기본 언어 설정
  Dokgi.xcodeproj/project.pbxproj
  Dokgi/ko.lproj/LaunchScreen.strings
Labels: ⚙ Setting, 🌏 Deploy

#112 Refactor/#107 구절 추가 화면 파일분리
  Dokgi.xcodeproj/project.pbxproj
  Dokgi/Extension/addSubviewsExtension.swift
  Dokgi/View/AddPassageView/Cell/KeywordCell.swift
  Dokgi/View/AddPassageView/View/AddPassageContainerView.swift
  Dokgi/View/AddPassageView/View/BookSearchContainerView.swift
  Dokgi/View/AddPassageView/ViewController/AddPassageViewController.swift
  Dokgi/View/AddPassageView/ViewController/BookSearchViewController.swift
  Dokgi/ViewModel/AddPassageViewModel/AddPassageViewModel.swift
  Dokgi/ViewModel/BookSearchViewModel/BookSearchViewModel.swift
Labels: 🔨 Refactor

#119 책 상세 코드 리팩토링
  Dokgi/Extension/DateExtension.swift
  Dokgi/Model/CoreData/CoreDataManager.swift
  Dokgi/View/BookDetailView/Cell/PassageTableViewCell.swift
  Dokgi/View/BookDetailView/ViewController/BookDetailViewController.swift
  Dokgi/View/LibraryView/ViewController/LibraryViewController.swift
  Dokgi/View/PassageDetailView/Cell/KeywordCollectionViewCell.swift
  Dokgi/ViewModel/BookDetailViewModel/BookDetailViewModel.swift
Labels: 🔨 Refactor

#120 Feat/#114 구절 추가 화면 코드 리팩토링
  Dokgi.xcodeproj/project.pbxproj
  Dokgi.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Dokgi/View/AddPassageView/Cell/KeywordCell.swift
  Dokgi/View/AddPassageView/Cell/RecentSearchCell.swift
  Dokgi/View/AddPassageView/View/AddPassageContainerView.swift
  Dokgi/View/AddPassageView/View/BookSearchContainerView.swift
  Dokgi/View/AddPassageView/View/InfoView.swift
  Dokgi/View/AddPassageView/ViewController/AddPassageViewController.swift
  Dokgi/View/AddPassageView/ViewController/BookSearchViewController.swift
  Dokgi/View/PassageDetailView/Cell/KeywordCollectionViewCell.swift
  Dokgi/ViewModel/AddPassageViewModel/AddPassageViewModel.swift
  Dokgi/ViewModel/BookSearchViewModel/BookSearchViewModel.swift
Labels: ✨ Feature

#123 [Feat] 구절 상세화면, 알림 코어데이터 연결
  Dokgi/View/PassageDetailView/ViewController/PassageDetailViewController.swift
  Dokgi/ViewModel/PassageDetailViewModel/PassageDetailViewModel.swift
  Dokgi/ViewModel/SettingViewModel/DayTimeViewModel.swift
Labels: ✨ Feature

#127 책 상세, 위젯 코어데이터 연결
  Dokgi.xcodeproj/project.pbxproj
  Dokgi/Model/CoreData/CoreDataManager.swift
  Dokgi/View/BookDetailView/Cell/PassageTableViewCell.swift
  Dokgi/View/BookDetailView/ViewController/BookDetailViewController.swift
  Dokgi/ViewModel/BookDetailViewModel/BookDetailViewModel.swift
  DokgiWidget/DokgiWidget.swift
Labels: 🔨 Refactor, ✨ Feature

#126 [Feat]#124-구절상세화면, 설정화면 리팩토링
  Dokgi.xcodeproj/project.pbxproj
  Dokgi/Extension/TextFieldExtension.swift
  Dokgi/View/PassageDetailView/View/PassageDetailContainerView.swift
  Dokgi/View/PassageDetailView/ViewController/PassageDetailViewController.swift
  Dokgi/View/SettingView/ViewController/SettingViewController.swift
  Dokgi/View/SettingView/ViewController/TimePickerViewController.swift
Labels: 🔨 Refactor

#130 내 구절, 내 서재 파일 분리
  Dokgi.xcodeproj/project.pbxproj
  Dokgi/View/LibraryView/Cell/LibraryCollectionViewCell.swift
  Dokgi/View/LibraryView/ViewController/LibraryCollectionView.swift
  Dokgi/View/LibraryView/ViewController/LibraryView.swift
  Dokgi/View/LibraryView/ViewController/LibraryViewController.swift
  Dokgi/View/PassageDetailView/ViewController/PassageDetailViewController.swift
  Dokgi/View/PassageView/ViewController/PassageCollectionView.swift
  Dokgi/View/PassageView/ViewController/PassageView.swift
  Dokgi/View/PassageView/ViewController/PassageViewController.swift
  Dokgi/ViewModel/PassageDetailViewModel/PassageDetailViewModel.swift
  Dokgi/ViewModel/PassageViewModel/PassageViewModel.swift
Labels: 🔨 Refactor

#134 구절 추가 화면 코어데이터 연결
  Dokgi/View/AddPassageView/ViewController/AddPassageViewController.swift
  Dokgi/ViewModel/AddPassageViewModel/AddPassageViewModel.swift
Labels: 🔨 Refactor, ✨ Feature

#135 Feat/#129 알림및 설정화면 오류수정
  Dokgi/Application/AppDelegate.swift
  Dokgi/View/Components/BaseAlarmSettingSheetViewController.swift
  Dokgi/View/SettingView/Cell/DayTableViewCell.swift
  Dokgi/View/SettingView/View/AlarmView.swift
  Dokgi/View/SettingView/ViewController/DaySelectViewController.swift
  Dokgi/View/SettingView/ViewController/SettingViewController.swift
  Dokgi/View/SettingView/ViewController/TimePickerViewController.swift
  Dokgi/ViewModel/SettingViewModel/DayTimeViewModel.swift
Labels: ✨ Feature

#141 내 서재, 구절 코어데이터 연결
  Dokgi/View/LibraryView/ViewController/LibraryViewController.swift
  Dokgi/View/PassageView/ViewController/PassageViewController.swift
  Dokgi/ViewModel/LibraryViewModel/LibraryViewModel.swift
  Dokgi/ViewModel/PassageViewModel/PassageViewModel.swift
Labels: 🔨 Refactor, ✨ Feature

#142 [Feat] 구절상세화면 수정
  Dokgi/Extension/TextFieldExtension.swift
  Dokgi/Resource/Assets.xcassets/icons/copyicon.imageset/Contents.json
  Dokgi/Resource/Assets.xcassets/icons/copyicon.imageset/Group.svg
  Dokgi/View/PassageDetailView/View/PassageDetailContainerView.swift
  Dokgi/View/PassageDetailView/ViewController/PassageDetailViewController.swift
Labels: ✨ Feature

#143 [Feat]#128-홈 화면 코어데이터 연결
  Dokgi/View/HomeView/View/HomeView.swift
  Dokgi/View/HomeView/ViewController/HomeViewController.swift
  Dokgi/ViewModel/HomeViewModel/HomeViewModel.swift
Labels: ✨ Feature

#145 Feat/#144 홈화면 오류 수정
  Dokgi/Model/UserDefaults/UserDefaultsKey.swift
  Dokgi/View/HomeView/Cell/CurrentLevelCell.swift
  Dokgi/View/HomeView/ViewController/HomeViewController.swift
  Dokgi/ViewModel/HomeViewModel/HomeViewModel.swift
Labels: ✨ Feature

#147 [Feat] 코어데이터 모델변경
  Dokgi.xcodeproj/project.pbxproj
  Dokgi/Dokgi.xcdatamodeld/.xccurrentversion
  Dokgi/Dokgi.xcdatamodeld/Dokgi 2.xcdatamodel/contents
  Dokgi/DokgiV1ToV2.xcmappingmodel/xcmapping.xml
  Dokgi/DokgiV1ToV2MigrationPolicy.swift
  Dokgi/Model/CoreData/CoreDataManager.swift
  Dokgi/Model/CoreData/VerseModel.swift
  Dokgi/View/AddPassageView/ViewController/AddPassageViewController.swift
  Dokgi/View/BookDetailView/Cell/PassageTableViewCell.swift
  Dokgi/View/BookDetailView/ViewController/BookDetailViewController.swift
  Dokgi/View/HomeView/ViewController/HomeViewController.swift
  Dokgi/View/LibraryView/ViewController/LibraryViewController.swift
  Dokgi/View/PassageDetailView/ViewController/PassageDetailViewController.swift
  Dokgi/View/PassageView/ViewController/PassageViewController.swift
  Dokgi/ViewModel/AddPassageViewModel/AddPassageViewModel.swift
  Dokgi/ViewModel/BookDetailViewModel/BookDetailViewModel.swift
  Dokgi/ViewModel/HomeViewModel/HomeViewModel.swift
  Dokgi/ViewModel/LibraryViewModel/LibraryViewModel.swift
  Dokgi/ViewModel/PassageDetailViewModel/PassageDetailViewModel.swift
  Dokgi/ViewModel/PassageViewModel/PassageViewModel.swift
  Dokgi/ViewModel/SettingViewModel/DayTimeViewModel.swift
  DokgiWidget/DokgiWidget.swift
Labels: ✨ Feature

#146 Feat/#131 - 내 서재, 내 구절 코드 리팩토링
  Dokgi.xcodeproj/project.pbxproj
  Dokgi/View/Components/BaseLibraryAndPassageViewController.swift
  Dokgi/View/Components/SortButton.swift
  Dokgi/View/Components/SortMenuView.swift
  Dokgi/View/LibraryView/ViewController/LibraryCollectionView.swift
  Dokgi/View/LibraryView/ViewController/LibraryView.swift
  Dokgi/View/LibraryView/ViewController/LibraryViewController.swift
  Dokgi/View/PassageView/ViewController/PassageCollectionView.swift
  Dokgi/View/PassageView/ViewController/PassageView.swift
  Dokgi/View/PassageView/ViewController/PassageViewController.swift
  Dokgi/ViewModel/PassageViewModel/PassageViewModel.swift
Labels: 🔨 Refactor

#151 [Feat] 구절화면
  Dokgi/Model/CoreData/CoreDataManager.swift
  Dokgi/View/PassageView/Cell/PassageCollectionViewCell.swift
  Dokgi/View/PassageView/ViewController/PassageViewController.swift
  Dokgi/ViewModel/PassageViewModel/PassageViewModel.swift
Labels: ✨ Feature

#152 Update README.md
  README.md
Labels: 📃 Docs

#153 [Feat]#150- 홈 화면 수정
  Dokgi/View/HomeView/Cell/CurrentLevelCell.swift
  Dokgi/View/HomeView/View/HomeView.swift
  Dokgi/View/HomeView/ViewController/HomeViewController.swift
Labels: ✨ Feature

#154 구절 추가 화면 수정
  Dokgi.xcodeproj/project.pbxproj
  Dokgi/Network/BookModel.swift
  Dokgi/Resource/Assets.xcassets/Color/searchButtonBlue.colorset/Contents.json
  Dokgi/View/AddPassageView/Cell/BookCell.swift
  Dokgi/View/AddPassageView/View/AddPassageContainerView.swift
  Dokgi/View/AddPassageView/View/BookSearchContainerView.swift
  Dokgi/View/AddPassageView/View/InfoView.swift
  Dokgi/View/AddPassageView/ViewController/AddPassageViewController.swift
  Dokgi/View/Components/SearchBar.swift
  Dokgi/ViewModel/AddPassageViewModel/AddPassageViewModel.swift
Labels: ✨ Feature

#155 Feat/#149 - 내 서재 수정
  Dokgi/Model/CoreData/CoreDataManager.swift
  Dokgi/View/BookDetailView/ViewController/BookDetailViewController.swift
  Dokgi/View/Components/BaseLibraryAndPassageViewController.swift
  Dokgi/View/LibraryView/Cell/LibraryCollectionViewCell.swift
  Dokgi/View/LibraryView/ViewController/LibraryViewController.swift
  Dokgi/View/PassageView/Cell/PassageCollectionViewCell.swift
  Dokgi/View/PassageView/ViewController/PassageViewController.swift
  Dokgi/ViewModel/LibraryViewModel/LibraryViewModel.swift
Labels: ✨ Feature

#157 [Fix]#156-책 상세 다크모드 대응 및 오류 수정
  Dokgi/View/BookDetailView/ViewController/BookDetailViewController.swift
  Dokgi/View/LibraryView/ViewController/LibraryViewController.swift
Labels: 🐞 BugFix

#161 [Feat]#158-런치스크린 다크모드 대응
  Dokgi/Base.lproj/LaunchScreen.storyboard
Labels: ✨ Feature

#163 [Fix] 구절화면 오류 수정2차
  Dokgi/Model/CoreData/CoreDataManager.swift
  Dokgi/View/PassageDetailView/ViewController/PassageDetailViewController.swift
  Dokgi/View/PassageView/ViewController/PassageViewController.swift
  Dokgi/View/TabBarView/TabBarViewController.swift
  Dokgi/ViewModel/PassageDetailViewModel/PassageDetailViewModel.swift
Labels: 🐞 BugFix

#166 구절 추가 화면 오류 수정 2차
  Dokgi/View/AddPassageView/Cell/BookCell.swift
  Dokgi/View/AddPassageView/View/AddPassageContainerView.swift
  Dokgi/View/AddPassageView/View/BookSearchContainerView.swift
  Dokgi/View/AddPassageView/ViewController/AddPassageViewController.swift
  Dokgi/View/AddPassageView/ViewController/BookSearchViewController.swift
  Dokgi/View/BookDetailView/ViewController/BookDetailViewController.swift
  Dokgi/View/TabBarView/TabBarViewController.swift
  Dokgi/ViewModel/AddPassageViewModel/AddPassageViewModel.swift
Labels: 🐞 BugFix

#167 [Feat]#164-오늘의구절 수정
  Dokgi/View/HomeView/ViewController/HomeViewController.swift
  Dokgi/ViewModel/HomeViewModel/HomeViewModel.swift
Labels: ✨ Feature

#168 Fix/#162 위젯 오류, 구절 추가하면 바로 반영
  Dokgi.xcodeproj/project.pbxproj
  Dokgi/View/BookDetailView/ViewController/BookDetailViewController.swift
  Dokgi/View/TabBarView/TabBarViewController.swift
  DokgiWidget/DokgiWidget.swift
Labels: 🐞 BugFix

#169 Fix/#165 내 서재 오토레이아웃 수정
  Dokgi/View/LibraryView/Cell/LibraryCollectionViewCell.swift
  Dokgi/View/LibraryView/ViewController/LibraryCollectionView.swift
Labels: 🐞 BugFix

#172 구절 추가 네비게이션 이동 오류, 구절 스캔 수정
  Dokgi/View/AddPassageView/View/AddPassageContainerView.swift
  Dokgi/View/BookDetailView/ViewController/BookDetailViewController.swift
Labels: 🐞 BugFix

#173 Fix/#171 서재 검색 중 구절 추가 시 / 책 추가 구절 스캔 버튼 / 책 검색 최근 검색어 수정
  Dokgi/Model/CoreData/CoreDataManager.swift
  Dokgi/View/AddPassageView/View/AddPassageContainerView.swift
  Dokgi/View/AddPassageView/View/BookSearchContainerView.swift
  Dokgi/View/AddPassageView/ViewController/BookSearchViewController.swift
  Dokgi/View/LibraryView/ViewController/LibraryViewController.swift
Labels: 🐞 BugFix

#179 OCR오류 수정
  Dokgi.xcodeproj/project.pbxproj
  Dokgi/View/AddPassageView/ViewController/AddPassageViewController.swift
Labels: 🐞 BugFix

#180 OCR 오류 수정 반영
  Dokgi.xcodeproj/project.pbxproj
  Dokgi/View/AddPassageView/ViewController/AddPassageViewController.swift
  README.md
Labels: 🐞 BugFix

#183 [Fix]#182-OCR 텍스트뷰 textColor 수정
  Dokgi/View/AddPassageView/ViewController/AddPassageViewController.swift
Labels: 🐞 BugFix

#181 [Fix] 오류수정 3차
  Dokgi/View/AddPassageView/View/InfoView.swift
  Dokgi/View/BookDetailView/ViewController/BookDetailViewController.swift
  Dokgi/View/HomeView/Cell/CurrentLevelCell.swift
  Dokgi/View/PassageDetailView/ViewController/PassageDetailViewController.swift
  DokgiWidget/DokgiWidget.swift
Labels: 🐞 BugFix

#184 OCR 오류 수정 & 3차 오류 수정
  Dokgi/View/AddPassageView/View/InfoView.swift
  Dokgi/View/AddPassageView/ViewController/AddPassageViewController.swift
  Dokgi/View/BookDetailView/ViewController/BookDetailViewController.swift
  Dokgi/View/HomeView/Cell/CurrentLevelCell.swift
  Dokgi/View/PassageDetailView/ViewController/PassageDetailViewController.swift
  DokgiWidget/DokgiWidget.swift
Labels: 🐞 BugFix
